package h

import "github.com/yogisalomo/goowee/core"

func Div(items ...core.Item) *core.ElementNode        { return El("div", items...) }
func Span(items ...core.Item) *core.ElementNode       { return El("span", items...) }
func P(items ...core.Item) *core.ElementNode          { return El("p", items...) }
func H1(items ...core.Item) *core.ElementNode         { return El("h1", items...) }
func H2(items ...core.Item) *core.ElementNode         { return El("h2", items...) }
func H3(items ...core.Item) *core.ElementNode         { return El("h3", items...) }
func H4(items ...core.Item) *core.ElementNode         { return El("h4", items...) }
func H5(items ...core.Item) *core.ElementNode         { return El("h5", items...) }
func H6(items ...core.Item) *core.ElementNode         { return El("h6", items...) }
func A(items ...core.Item) *core.ElementNode          { return El("a", items...) }
func Ul(items ...core.Item) *core.ElementNode         { return El("ul", items...) }
func Ol(items ...core.Item) *core.ElementNode         { return El("ol", items...) }
func Li(items ...core.Item) *core.ElementNode         { return El("li", items...) }
func Dl(items ...core.Item) *core.ElementNode         { return El("dl", items...) }
func Dt(items ...core.Item) *core.ElementNode         { return El("dt", items...) }
func Dd(items ...core.Item) *core.ElementNode         { return El("dd", items...) }
func Form(items ...core.Item) *core.ElementNode       { return El("form", items...) }
func Button(items ...core.Item) *core.ElementNode     { return El("button", items...) }
func Label(items ...core.Item) *core.ElementNode      { return El("label", items...) }
func Select(items ...core.Item) *core.ElementNode     { return El("select", items...) }
func Option(items ...core.Item) *core.ElementNode     { return El("option", items...) }
func Optgroup(items ...core.Item) *core.ElementNode   { return El("optgroup", items...) }
func Textarea(items ...core.Item) *core.ElementNode   { return El("textarea", items...) }
func Nav(items ...core.Item) *core.ElementNode        { return El("nav", items...) }
func Main(items ...core.Item) *core.ElementNode       { return El("main", items...) }
func Section(items ...core.Item) *core.ElementNode    { return El("section", items...) }
func Header(items ...core.Item) *core.ElementNode     { return El("header", items...) }
func Footer(items ...core.Item) *core.ElementNode     { return El("footer", items...) }
func Article(items ...core.Item) *core.ElementNode    { return El("article", items...) }
func Aside(items ...core.Item) *core.ElementNode      { return El("aside", items...) }
func Strong(items ...core.Item) *core.ElementNode     { return El("strong", items...) }
func Em(items ...core.Item) *core.ElementNode         { return El("em", items...) }
func B(items ...core.Item) *core.ElementNode          { return El("b", items...) }
func I(items ...core.Item) *core.ElementNode          { return El("i", items...) }
func U(items ...core.Item) *core.ElementNode          { return El("u", items...) }
func Small(items ...core.Item) *core.ElementNode      { return El("small", items...) }
func Code(items ...core.Item) *core.ElementNode       { return El("code", items...) }
func Pre(items ...core.Item) *core.ElementNode        { return El("pre", items...) }
func Blockquote(items ...core.Item) *core.ElementNode { return El("blockquote", items...) }
func Figure(items ...core.Item) *core.ElementNode     { return El("figure", items...) }
func Figcaption(items ...core.Item) *core.ElementNode { return El("figcaption", items...) }
func Table(items ...core.Item) *core.ElementNode      { return El("table", items...) }
func Thead(items ...core.Item) *core.ElementNode      { return El("thead", items...) }
func Tbody(items ...core.Item) *core.ElementNode      { return El("tbody", items...) }
func Tfoot(items ...core.Item) *core.ElementNode      { return El("tfoot", items...) }
func Tr(items ...core.Item) *core.ElementNode         { return El("tr", items...) }
func Th(items ...core.Item) *core.ElementNode         { return El("th", items...) }
func Td(items ...core.Item) *core.ElementNode         { return El("td", items...) }
func Caption(items ...core.Item) *core.ElementNode    { return El("caption", items...) }
func Details(items ...core.Item) *core.ElementNode    { return El("details", items...) }
func Summary(items ...core.Item) *core.ElementNode    { return El("summary", items...) }
func Dialog(items ...core.Item) *core.ElementNode     { return El("dialog", items...) }
func Fieldset(items ...core.Item) *core.ElementNode   { return El("fieldset", items...) }
func Legend(items ...core.Item) *core.ElementNode     { return El("legend", items...) }
func Progress(items ...core.Item) *core.ElementNode   { return El("progress", items...) }
func Iframe(items ...core.Item) *core.ElementNode     { return El("iframe", items...) }
func Video(items ...core.Item) *core.ElementNode      { return El("video", items...) }
func Audio(items ...core.Item) *core.ElementNode      { return El("audio", items...) }
func Canvas(items ...core.Item) *core.ElementNode     { return El("canvas", items...) }

func Br(items ...core.Item) *core.ElementNode     { return El("br", items...) }
func Hr(items ...core.Item) *core.ElementNode     { return El("hr", items...) }
func Img(items ...core.Item) *core.ElementNode    { return El("img", items...) }
func Input(items ...core.Item) *core.ElementNode  { return El("input", items...) }
func Source(items ...core.Item) *core.ElementNode { return El("source", items...) }
func Track(items ...core.Item) *core.ElementNode  { return El("track", items...) }
func Wbr(items ...core.Item) *core.ElementNode    { return El("wbr", items...) }
func Area(items ...core.Item) *core.ElementNode   { return El("area", items...) }
func Col(items ...core.Item) *core.ElementNode    { return El("col", items...) }
func Embed(items ...core.Item) *core.ElementNode  { return El("embed", items...) }
